---
title: "Exploratory Data Analysis: Peer assessment 2-ReadME"
output: html_document
---

This project uses data from the National Emissions Inventory (NEI) database, 
released by the Environmental Protection Agency (EPA), which reports the number 
of tons of fine particulate matter (PM2.5) emitted by a given source over the 
course of a given year. This assignment focuses in particular on data for 1999, 
2002, 2005, and 2008.

The following questions were posed to assess exploratory analytical skills, and the answers are represented with graphs and contained as comments in the corresponding R file:

1. Have total emissions from PM2.5 decreased in the United States from 1999 to 2008?
2. Have total emissions from PM2.5 decreased in the Baltimore City, Maryland from 1999 to 2008?
3. Of the four types of sources indicated by the type (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999–2008 for Baltimore City? Which have seen increases in emissions from 1999–2008?
4. Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008?


##Loading and pre-processing data
The following is the code used to download and unzip the data:
```{r, echo=TRUE}
setwd("F:/Data_Science_Coursera/Exploratory_Data_Analysis/CourseProject2")
library(ggplot2)
library(lattice)
library(data.table)

download.file(url = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", destfile = "NEI_data.zip")
unzip(zipfile = "NEI_data.zip", exdir = ".")
file.remove("NEI_data.zip")
```

The data itself is located in summarySCC_PM25.rds.

The codebook for the data is locaed in Source_Classification_Code.rds.

The files were read into r using readRDS() and the datafile was stored as a data table using the data.table package.

The plots and r codes for each plot are saved as six separate files, one for each question. Each r file contains code to read the data in, although the data was only read in once for the purpose of the actual assignment.
